const express = require("express");
const authRoutes = require("../modules/auth/auth.routes");
const adminAuthRoutes = require("../modules/auth/adminAuth.routes");
const productsRoutes = require("../modules/products/products.routes");
const categoriesRoutes = require("../modules/categories/categories.routes");
const threadColoursRoutes = require("../modules/threadColours/threadColours.routes");
const quotesRoutes = require("../modules/quotes/quotes.routes");
const attachmentsRoutes = require("../modules/attachments/attachments.routes");
const adminQuotesRoutes = require("../modules/admin/adminQuotes.routes");
const adminOrdersRoutes = require("../modules/admin/adminOrders.routes");
const adminProductsRoutes = require("../modules/admin/adminProducts.routes");
const adminCategoriesRoutes = require("../modules/admin/adminCategories.routes");
const adminThreadColoursRoutes = require("../modules/admin/adminThreadColours.routes");
const adminSettingsRoutes = require("../modules/admin/adminSettings.routes");
const adminPoliciesRoutes = require("../modules/admin/adminPolicies.routes");
const ratingsRoutes = require("../modules/ratings/ratings.routes");
const homeStatsRoutes = require("../modules/homeStats/homeStats.routes");
const invoicesRoutes = require("../modules/invoices/invoices.routes");
const vatRatesRoutes = require("../modules/vatRates/vatRates.routes");
const shippingRatesRoutes = require("../modules/shippingRates/shippingRates.routes");
const ordersRoutes = require("../modules/orders/orders.routes");
const policiesRoutes = require("../modules/policies/policies.routes");

const router = express.Router();

router.use("/auth", authRoutes);
router.use("/admin/auth", adminAuthRoutes);
router.use("/", productsRoutes);
router.use("/", categoriesRoutes);
router.use("/", threadColoursRoutes);
router.use("/", homeStatsRoutes);
router.use("/quotes", quotesRoutes);
router.use("/quotes/:quoteId/attachments", attachmentsRoutes);
router.use("/products/:id/rating", ratingsRoutes);
router.use("/admin/quotes", adminQuotesRoutes);
router.use("/admin/orders", adminOrdersRoutes);
router.use("/admin/products", adminProductsRoutes);
router.use("/admin/categories", adminCategoriesRoutes);
router.use("/admin/thread-colours", adminThreadColoursRoutes);
router.use("/admin/settings", adminSettingsRoutes);
router.use("/admin/policies", adminPoliciesRoutes);
router.use("/admin/invoices", invoicesRoutes);
router.use("/admin/vat-rates", vatRatesRoutes);
router.use("/admin/shipping-rates", shippingRatesRoutes);
router.use("/account/orders", ordersRoutes);
router.use("/policies", policiesRoutes);

module.exports = router;
